package services;

import dao.WasteRecordDAO;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;

/**
 * Service class for waste data operations.
 * Encapsulates waste records and provides controlled access through methods.
 * Data is now stored in H2 database via WasteRecordDAO.
 */
public class WasteDataService {
    // Cache records per role: {role -> List of records}
    private static final java.util.Map<String, List<Object[]>> roleRecords = new java.util.HashMap<>();

    /**
     * Gets all waste records for a specific role.
     * @param role The user's role
     * @return List of waste records {id, date, area, weight, type}
     */
    public static List<Object[]> getAllRecords(String role) {
        // Check cache first
        if (roleRecords.containsKey(role)) {
            return Collections.unmodifiableList(roleRecords.get(role));
        }
        
        // Load from database
        try {
            List<Object[]> dbRecords = WasteRecordDAO.getWasteRecordsByRole(role);
            // Convert from {id, role, date, area, weight, type} to {id, date, area, weight, type}
            List<Object[]> convertedRecords = new ArrayList<>();
            for (Object[] record : dbRecords) {
                // DB format: {id, role, date, area, weight, type}
                // Service format: {id, date, area, weight, type}
                convertedRecords.add(new Object[]{
                    record[0], // id
                    record[2], // date
                    record[3], // area
                    record[4], // weight
                    record[5]  // type
                });
            }
            roleRecords.put(role, convertedRecords);
            return Collections.unmodifiableList(convertedRecords);
        } catch (SQLException e) {
            System.err.println("Error loading waste records from database: " + e.getMessage());
            e.printStackTrace();
            return Collections.unmodifiableList(new ArrayList<>());
        }
    }
    
    /**
     * Clears the cache for a role, forcing a reload from database on next access.
     * Useful when you want to ensure fresh data is loaded.
     * @param role The user's role
     */
    public static void clearCache(String role) {
        roleRecords.remove(role);
    }

    /**
     * Adds a new waste record to the system for a specific role.
     * First saves to .txt file (based on role), then automatically imports to database.
     * @param role The user's role
     * @param date The date of the record
     * @param area The area/location
     * @param weight The weight in kg
     * @param type The waste type
     */
    public static void addRecord(String role, String date, String area, double weight, String type) {
        // Step 1: Save to .txt file first (based on role)
        String filePath = RoleDataFileService.getDataFilePath(role);
        File txtFile = new File(filePath);
        
        try {
            // Ensure data directory exists
            txtFile.getParentFile().mkdirs();
            
            // Append to .txt file (pipe-delimited format: id|date|area|weight|type)
            // Note: id will be generated by database, so we use placeholder or let DB generate
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(txtFile, true))) {
                // Check if file is empty or doesn't exist, write header
                if (!txtFile.exists() || txtFile.length() == 0) {
                    writer.write("# Waste Records for " + role);
                    writer.newLine();
                    writer.write("# Format: id|date|area|weight|type");
                    writer.newLine();
                    writer.newLine();
                }
                
                // Write waste record data (id will be generated by database, use 0 as placeholder)
                writer.write("0|" + date + "|" + area + "|" + weight + "|" + type);
                writer.newLine();
                writer.flush();
            }
            
            // Step 2: Automatically import from .txt to database
            int newId = WasteRecordDAO.createWasteRecord(role, date, area, weight, type);
            if (newId > 0) {
                // Clear cache to force reload
                clearCache(role);
            }
        } catch (IOException e) {
            System.err.println("Error writing to .txt file: " + e.getMessage());
            e.printStackTrace();
            // Still try to save to database even if .txt write fails
            try {
                int newId = WasteRecordDAO.createWasteRecord(role, date, area, weight, type);
                if (newId > 0) {
                    clearCache(role);
                }
            } catch (SQLException sqlEx) {
                System.err.println("Error adding waste record to database: " + sqlEx.getMessage());
                sqlEx.printStackTrace();
            }
        } catch (SQLException e) {
            System.err.println("Error adding waste record to database: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Deletes a waste record by ID for a specific role.
     * @param role The user's role
     * @param id The ID of the record to delete
     */
    public static void deleteRecord(String role, int id) {
        try {
            boolean success = WasteRecordDAO.deleteWasteRecord(id);
            if (success) {
                // Clear cache to force reload
                clearCache(role);
            }
        } catch (SQLException e) {
            System.err.println("Error deleting waste record from database: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * Updates records from table model.
     * Note: This method currently doesn't update the database directly.
     * Individual records should be updated using update methods if needed.
     * @param role The user's role
     * @param model The table model containing updated data
     */
    public static void clearAndReload(String role, DefaultTableModel model) {
        // Clear cache to force reload from database
        clearCache(role);
        // Data will be reloaded on next getAllRecords() call
    }

    /**
     * Returns all waste records in raw DAO format for reporting.
     * Format: {id, role, date, area, weight, type}
     */
    public static java.util.List<Object[]> getAllWasteRecordsForReport() {
        try {
            return WasteRecordDAO.getAllWasteRecords();
        } catch (SQLException e) {
            System.err.println("Error loading waste records for report: " + e.getMessage());
            e.printStackTrace();
            return java.util.Collections.emptyList();
        }
    }

    /**
     * Exports all waste records to a CSV file.
     * Columns: id,role,date,area,weight,type
     *
     * @param file target file (CSV or .txt)
     * @return true if successful, false otherwise
     */
    public static boolean exportWasteRecordsToCsv(File file) {
        if (file == null) return false;
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            writer.write("id,role,date,area,weight,type");
            writer.newLine();

            java.util.List<Object[]> all = WasteRecordDAO.getAllWasteRecords();
            for (Object[] rec : all) {
                String line = String.format("%s,%s,%s,%s,%s,%s",
                        safeCsv(rec[0]),
                        safeCsv(rec[1]),
                        safeCsv(rec[2]),
                        safeCsv(rec[3]),
                        safeCsv(rec[4]),
                        safeCsv(rec[5])
                );
                writer.write(line);
                writer.newLine();
            }
            writer.flush();
            return true;
        } catch (IOException | SQLException e) {
            System.err.println("Error exporting waste records to CSV: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    private static String safeCsv(Object value) {
        if (value == null) return "";
        String text = String.valueOf(value);
        if (text.contains(",") || text.contains("\"") || text.contains("\n")) {
            text = text.replace("\"", "\"\"");
            return "\"" + text + "\"";
        }
        return text;
    }

    /**
     * Imports waste records from a .txt file (pipe-delimited format).
     * Format: id|date|location|weight|type|barangay
     * Example: 1|2025-12-07|Casa Verde|15.0|Malata (Biodegradable)|Central
     * 
     * @param file The .txt file to import from
     * @param role The role to assign to imported records (e.g., "Garbage Collector")
     * @return Number of records successfully imported
     */
    public static int importWasteRecordsFromTxt(File file, String role) {
        if (file == null || !file.exists()) {
            return 0;
        }
        
        int imported = 0;
        int skipped = 0;
        
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                // Skip empty lines and comments
                if (line.isEmpty() || line.startsWith("#")) {
                    continue;
                }
                
                // Parse pipe-delimited format: id|date|location|weight|type|barangay
                String[] parts = line.split("\\|");
                if (parts.length < 6) {
                    skipped++;
                    continue;
                }
                
                try {
                    // parts[0] = id (we'll ignore this, let DB generate new ID)
                    String date = parts[1].trim();
                    String location = parts[2].trim();
                    double weight = Double.parseDouble(parts[3].trim());
                    String type = parts[4].trim();
                    // parts[5] = barangay (not stored in waste_records table, but we use location)
                    
                    // Create record in database
                    int newId = WasteRecordDAO.createWasteRecord(role, date, location, weight, type);
                    if (newId > 0) {
                        imported++;
                    } else {
                        skipped++;
                    }
                } catch (NumberFormatException | SQLException e) {
                    System.err.println("Error importing line: " + line + " - " + e.getMessage());
                    skipped++;
                }
            }
            
            // Clear cache after import
            clearCache(role);
            
            System.out.println("Import complete: " + imported + " records imported, " + skipped + " skipped");
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
            e.printStackTrace();
        }
        
        return imported;
    }
}
